### ISSUE TITLE
What is the leadership board for the CLEVR dataset in Machine Learning?

### ISSUE THREAD

**Issue by brando90** [facebookresearch/clevr-dataset-gen#16]
Where is a list to the papers with all the benchmarks and models done to this data set?

https://www.quora.com/unanswered/What-is-the-leadership-board-the-the-CLEVER-dataset-in-Machine-Learning

**Comment by jcjohnson** [comment]
We don't have an official leaderboard.

**Comment by brando90** [comment]
is there a rough list of ANY papers that solve this task?

**Comment by jcjohnson** [comment]
I'm not sure of the current state-of-the-art; you'll need to do a literature search. CAM is a good place to start (https://arxiv.org/abs/1803.03067); for module-network approaches you can take a look at (https://arxiv.org/abs/1902.07864) and references therein.
