### ISSUE TITLE
Blender compatible version

### ISSUE THREAD

**Issue by AvivSham** [facebookresearch/clevr-dataset-gen#22]
* Is this repo compatible with blender 2.8? if not which version should I install?
I recommend you to add this to the README file since this info is not included for now.

* Another question please: I saw json file example of generated image and under "pixel_coords" key there was a list of three values. What does the last value represent?

**Comment by jcjohnson** [comment]
I haven't tested any of this code with Blender 2.8, so I don't know if it will work. You should stick with 2.7.

The last value in pixel coords gives the z coordinate of the object center; I don't recall exactly what the units are, but you can use it to compare the relative depths of objects.
